# HTTP to HTTPS redirect
server {
    listen 80;
    server_name __DOMAIN__;
    return 301 https://__DOMAIN__$request_uri;
}

# WWW -> NON WWW
server {
    listen 443 ssl http2;
    server_name www.__DOMAIN__;
    ssl_certificate /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/__DOMAIN__/chain.pem;
    return 301 https://__DOMAIN__$request_uri;
}

server {
    listen 443 ssl http2;
    server_name __DOMAIN__;
    root __MOODLE_DIR__;

   # SSL
    ssl_certificate /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/__DOMAIN__/chain.pem;

    # index.php
    index index.php;

    # index.php fallback
location / {
        try_files $uri $uri/ /r.php$is_args$args;
        client_max_body_size 512M;
    }

    location ~ \.php(/|$) {
    fastcgi_split_path_info ^(.+\.php)(/.*)$;

    # Preserve path info
    set $path_info $fastcgi_path_info;

    # Ensure file exists, fallback to Moodle router
    try_files $fastcgi_script_name /r.php$is_args$args;

    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    fastcgi_index index.php;

    include fastcgi_params;

    # Use realpath for safety
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_param PATH_INFO $path_info;
}

    error_page 404 /error/index.php;
    error_page 403 =404 /error/index.php;

    location ~ /\.(?!well-known).* {
        return 404;
    }

    location ~ (/vendor/|/node_modules/|composer\.json|/readme|/README|readme\.txt|/upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md|db/install\.xml|/fixtures/|/behat/|phpunit\.xml|\.lock|environment\.xml) {
        deny all;
        return 404;
    }

    location /dataroot/ {
        internal;
        alias __MOODLE_DATA_DIR__;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy "strict-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), fullscreen=(self)";
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; sty>
 }
